name             "contentManagement_85"
maintainer       "IBM"
maintainer_email "flageuls@fr.ibm.com"
license          "Apache 2.0"
description      "IBM Content Management V8.5."
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "1.0"
depends		 "im_173"
depends		 "ibm_network_handler"
depends		 "was_v8551"
depends		 "websphereSDKjava_70"
depends		 "WebspherePortal_85"
depends		 "ihs_8550"
depends		 "ihs_8551"
depends		 "db2_ese_v105"
