name             "was_v70027"
maintainer       "IBM"
maintainer_email "rfjunior@br.ibm.com"
license          "Apache 2.0"
description      "WebSphere Application Server 7.0.0.27, profile creation."
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "1.0"
depends          "chef_handler"
depends			 "windows"
depends          "ibm_network_handler"
