---
driver_plugin: digitalocean
driver_config:
  digitalocean_client_id: <%= ENV['DIGITALOCEAN_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DIGITALOCEAN_API_KEY'] %>
  region_id: <%= ENV['DIGITALOCEAN_REGION_ID'] %>
  ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>
  ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY'] %>
  flavor_id: 66

platforms:
- name: chef-11_ubuntu-12.04
  driver_config:
    image_id: 284203
    require_chef_omnibus: true
- name: chef-10_ubuntu-12.04
  driver_config:
    image_id: 284203
    require_chef_omnibus: 10.28.2

- name: chef-11_ubuntu-10.04
  driver_config:
    image_id: 14097
    require_chef_omnibus: true
- name: chef-10_ubuntu-10.04
  driver_config:
    image_id: 14097
    require_chef_omnibus: 10.28.2

- name: chef-11_centos-6.4
  driver_config:
    image_id: 562354
    require_chef_omnibus: true
- name: chef-10_centos-6.4
  driver_config:
    image_id: 562354
    require_chef_omnibus: 10.28.2
    
- name: chef-11_centos-5.8
  driver_config:
    image_id: 1601
    require_chef_omnibus: true
- name: chef-10_centos-5.8
  driver_config:
    image_id: 1601
    require_chef_omnibus: 10.28.2
  
    
