name             "infosmdm_v11"
maintainer       "IBM, Inc."
maintainer_email "dasc@br.ibm.com"
license          "Apache 2.0"
description      "Provides a library to install the IBM InfoSphere MDM v11."
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "1.0.0"
depends          "ibm_network_handler"
depends			 "db2_ese_v105"
depends			 "was_v8552"
depends			 "im_173"