name             "wee_v62"
maintainer       "IBM, Inc."
maintainer_email "dasc@br.ibm.com"
license          "Apache 2.0"
description      "Provides a library to install the IBM Worklight Enterprise Edition v6.2."
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "1.0.0"
depends          "im"
depends          "wasl_v855"
depends          "db2_ese_v10"
depends          "ibm_network_handler"