name             "im"
maintainer       "IBM"
maintainer_email "dasc@br.ibm.com"
license          "Apache 2.0"
description      "IBM Installation Manager"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "1.0"
depends          "chef_handler"
depends          "windows"
depends          "ibm_network_handler"
