name             "ihs_8551"
maintainer       "IBM"
maintainer_email "flageuls@fr.ibm.com"
license          "Apache 2.0"
description      "WebSphere HTTP Server 8.5.5.1"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "2.0"
depends		 "im"
depends		 "ibm_network_handler"
depends		 "ihs_850"
